backend
backend/src
backend/src/ai
backend/src/ai/ai-trading-advisor.js
backend/src/ai/ml-engine.js
backend/src/ai/trading-advisor.js
backend/src/alerts
backend/src/alerts/alert-manager.js
backend/src/alerts/email-manager.js
backend/src/backtesting
backend/src/backtesting/backtest-engine.js
backend/src/backtesting/backtester.js
backend/src/backtesting/historical-data-manager.js
backend/src/core
backend/src/core/AlertManager.js
backend/src/core/cex-arbitrage-bot.js
backend/src/core/StrategyManager.js
backend/src/css
backend/src/css/dashboard.css
backend/src/exchanges
backend/src/exchanges
backend/src/exchanges/exchange-manager.js
backend/src/exchanges/exchanges.js
backend/src/exchanges/real-price-fetcher.js
backend/src/mobile
backend/src/mobile/mobile-api-desable.js
backend/src/mobile/mobile-api.js
backend/src/portfolio
backend/src/portfolio/portfolio-manager.js
backend/src/risk
backend/src/risk/advanced-risk-manager.js
backend/src/scripts
backend/src/scripts/run-backtest.js
backend/src/services
backend/src/services/api.js
backend/src/services/apiRoutes.js
backend/src/strategies
backend/src/strategies/config.js
backend/src/strategies/risk-management.js
backend/src/strategies/strategy-manager.js
backend/.env
backend/arbitrage-bot.js
backend/binance-test.js
backend/debug-alert-manager.js
backend/debug-telegram.js
backend/Guía_de_Inicio_Rápido.txt
backend/main-bot-updated.js
backend/Manual_Completo_del_Bot_La_Biblia.txt
backend/package-lock.json
backend/package.json
backend/Script_de_Configuración_Rápida.js
backend/server.js
backend/test-email.js
backend/test-telegram.js
frontend
frontend/public
frontend/public/components
frontend/public/components/AIPanel.jsx
frontend/public/components/App.jsx
frontend/public/components/ArbitrageOpportunities.jsx
frontend/public/components/AutoRebalance.jsx
frontend/public/components/BalanceChart.jsx
frontend/public/components/Controls.jsx
frontend/public/components/Header.jsx
frontend/public/components/ProfitChart.jsx
frontend/public/components/RiskAnalysis.jsx
frontend/public/components/Sidebar.jsx
frontend/public/components/SpecificPairs.jsx
frontend/public/components/StatusCard.jsx
frontend/public/js
frontend/public/js/advanced-dashboard.js
frontend/public/js/app.js
frontend/public/js/dashboard.js
frontend/public/js/mobile-api-client.js
frontend/public/index.html
frontend/public/styles.ccs
frontend/src
frontend/src/ai
frontend/src/ai/ai-trading-advisor.js
frontend/src/ai/ml-engine.js
frontend/src/ai/trading-advisor.js
frontend/src/alerts
frontend/src/alerts/alert-manager.js
frontend/src/alerts/email-manager.js
frontend/src/backtesting
frontend/src/backtesting/backtest-engine.js
frontend/src/backtesting/backtester.js
frontend/src/backtesting/historical-data-manager.js
frontend/src/components
frontend/src/contexts/AuthContext.jsx
frontend/src/contexts/BotContext.jsx
frontend/src/core
frontend/src/core/AlertManager.js
frontend/src/core/cex-arbitrage-bot.js
frontend/src/core/StrategyManager.js
frontend/src/css
frontend/src/css/dashboard.css
frontend/src/exchanges
frontend/src/exchanges/exchange-manager.js
frontend/src/exchanges/exchanges.js
frontend/src/exchanges/real-price-fetcher.js
frontend/src/mobile
frontend/src/mobile/mobile-api-desable.js
frontend/src/mobile/mobile-api.js
frontend/src/pages
frontend/src/pages/AIAdvisor.jsx
frontend/src/pages/AIPanel.jsx
frontend/src/pages/AlertsPanel.jsx
frontend/src/pages/AnomalyDetectionPanel.jsx
frontend/src/pages/ArbitragePanel.jsx
frontend/src/pages/BacktestingPanel.jsx
frontend/src/pages/BalancesRiskPanel.jsx
frontend/src/pages/CommissionPanel.jsx
frontend/src/pages/dashboard-pro.css
frontend/src/pages/dashboard.css
frontend/src/pages/Dashboard.jsx
frontend/src/pages/DepositAddressesPanel.jsx
frontend/src/pages/ExchangesPanel.jsx
frontend/src/pages/FeesPanel.jsx
frontend/src/pages/GeneralConfigPanel.jsx
frontend/src/pages/Login.jsx
frontend/src/pages/LogsPanel.jsx
frontend/src/pages/MetricsPanel.jsx
frontend/src/pages/mobile-api.js
frontend/src/pages/MobileApiPanel.jsx
frontend/src/pages/PairsPanel.jsx
frontend/src/pages/PortfolioPanel.jsx
frontend/src/pages/PricesPanel.jsx
frontend/src/pages/RebalancePanel.jsx
frontend/src/pages/RiskManagerPanel.jsx
frontend/src/pages/SecurityPanel.jsx
frontend/src/pages/SimulationSwitch.jsx
frontend/src/pages/StrategiesPanel.jsx
frontend/src/pages/StrategySelector.jsx
frontend/src/pages/TroubleshootingPanel.jsx
frontend/src/portfolio
frontend/src/portfolio/portfolio-manager.js
frontend/src/risk
frontend/src/risk/advanced-risk-manager.js
frontend/src/scripts
frontend/src/scripts/run-backtest.js
frontend/src/services
frontend/src/services/api.js
frontend/src/strategies
frontend/src/strategies/config.js
frontend/src/strategies/risk-management.js
frontend/src/strategies/strategy-manager.js
frontend/src/App.css
frontend/src/index.html
frontend/src/App.jsx
frontend/src/index.css
frontend/src/index.jsx
frontend/package-lock.json
frontend/package.json
package-lock.json
README.md
test-binance.js
Estructure.js
