public
public/components
public/components/AIPanel.jsx
public/components/App.jsx
public/components/ArbitrageOpportunities.jsx
public/components/AutoRebalance.jsx
public/components/BalanceChart.jsx
public/components/Controls.jsx
public/components/Header.jsx
public/components/ProfitChart.jsx
public/components/RiskAnalysis.jsx
public/components/SpecificPairs.jsx
public/components/StatusCard.jsx
public/js
public/js/advanced-dashboard.js
public/js/app.js
public/js/dashboard.js
public/js/mobile-api-client.js
public/js/risk-chart.js
public/js/strategies-manager.js
public/index.html
public/styles.ccs
scripts
scripts/run-backtest.js
src
src/ai
src/ai/ai-trading-advisor.js
src/ai/ml-engine.js
src/ai/trading-advisor.js
src/alerts
src/alerts/alert-manager.js
src/alerts/email-manager.js
src/backtesting
src/backtesting/backtest-engine.js
src/backtesting/backtester.js
src/backtesting/historical-data-manager.js
src/components
src/components/Layout.jsx
src/components/Sidebar.jsx
src/contexts
src/contexts/AuthContext.jsx
src/contexts/BotContext.jsx
src/core
src/core/AlertManager.js
src/core/cex-arbitrage-bot.js
src/core/StrategyManager.js
src/css
src/css/dashboard.css
src/exchanges
src/exchanges/exchange-manager.js
src/exchanges/exchanges.js
src/exchanges/real-price-fetcher.js
src/mobile
src/mobile/mobile-api-desable.js
src/mobile/mobile-api.js
src/pages
src/pages/AIAdvisor.jsx
src/pages/AlertsPanel.jsx
src/pages/AnomaliesPanel.jsx
src/pages/AnomalyDetectionPanel.jsx
src/pages/ArbitragePanel.jsx
src/pages/BacktestingPanel.jsx
src/pages/CommissionPanel.jsx
src/pages/Dashboard.jsx
src/pages/ExchangesPanel.jsx
src/pages/GeneralConfigPanel.jsx
src/pages/IAPanel.jsx
src/pages/Login.jsx
src/pages/LogsPanel.jsx
src/pages/MetricsPanel.jsx
src/pages/MobileApiPanel.jsx
src/pages/RebalancePanel.jsx
src/pages/RiskManagerPanel.jsx
src/pages/SecurityPanel.jsx
src/pages/SimulationSwitch.jsx
src/pages/StrategiesPanel.jsx
src/pages/StrategySelector.jsx
src/pages/TroubleshootingPanel.jsx
src/portfolio
src/portfolio/portfolio-manager.js
risk
risk/advanced-risk-manager.js
src/services
src/services/api.js
src/services/apiRoutes.js
src/strategies
src/strategies/estrategy-manager.js
src/strategies/config.js
src/strategies/risk-management.js
src/App.jsx
.env
arbitrage-bot.js
debug-alert-manager.js
debug-telegram.js
estructura.js
Guía_de_Inicio_Rápido.txt
main-bot-updated.js
Manual_Completo_del_Bot_La_Biblia.txt
package-lock.json
package.json
README.md
Script_de_Configuración_Rápida.js
server.js
test-binance.js
test-email.js
test-telegram.js